export enum QUERY_KEYS {
  GET_AUTHENTICATED_USER = "GET_AUTHENTICATED_USER",

  GET_NOTES = "GET_NOTES",
  GET_NOTE = "GET_NOTE",
  CREATE_NOTE = "CREATE_NOTE",
  UPDATE_NOTE = "UPDATE_NOTE",
  DELETE_NOTE = "DELETE_NOTE",
}
